# Only non OpenGL components of Yocto/GL are built
# This Travis file is a heavily modified version of https://github.com/nlohmann/json

version: '{build}'

os:
  - Visual Studio 2017

branches:
  only:
    - master
    - development

init: []

install: []

build_script:
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE (SET GEN="Visual Studio 15 2017")
  - cmake . -G%GEN% -DCMAKE_CXX_FLAGS="%additional_flags%" -DYOCTO_EMBREE=OFF
  - cmake --build . --config Release
